import defaultTheme from "tailwindcss/defaultTheme";
import forms from "@tailwindcss/forms";

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php",
        "./storage/framework/views/*.php",
        "./resources/views/**/*.blade.php",
    ],

    theme: {
        extend: {
            colors: {
                outline: "#94a3b8",
                "on-secondary-fixed": "#172554",
                "secondary-container": "#eff6ff",
                "inverse-primary": "#60a5fa",
                "tertiary-fixed-dim": "#7dd3fc",
                error: "#dc2626",
                surface: "#ffffff",
                "surface-container-high": "#e2e8f0",
                "tertiary-container": "#e0f2fe",
                "on-background": "#0f172a",
                "on-surface": "#0f172a",
                "surface-container-low": "#f8fafc",
                "primary-fixed": "#dbeafe",
                "inverse-on-surface": "#f8fafc",
                "surface-tint": "#2563eb",
                "surface-variant": "#f1f5f9",
                "on-secondary-container": "#1e40af",
                "secondary-fixed": "#eff6ff",
                primary: "#2563eb",
                "surface-bright": "#ffffff",
                "outline-variant": "#cbd5e1",
                "on-primary-fixed-variant": "#1d4ed8",
                "on-primary": "#ffffff",
                "on-primary-fixed": "#172554",
                "secondary-fixed-dim": "#bfdbfe",
                tertiary: "#0ea5e9",
                "primary-fixed-dim": "#93c5fd",
                "primary-container": "#dbeafe",
                secondary: "#3b82f6",
                "surface-container": "#f1f5f9",
                "on-tertiary-fixed-variant": "#0284c7",
                "surface-container-highest": "#cbd5e1",
                "on-surface-variant": "#475569",
                "on-secondary-fixed-variant": "#2563eb",
                "on-tertiary-fixed": "#082f49",
                "error-container": "#fecaca",
                "on-error": "#ffffff",
                "on-error-container": "#7f1d1d",
                "on-secondary": "#ffffff",
                "on-tertiary": "#ffffff",
                "surface-dim": "#e2e8f0",
                "tertiary-fixed": "#e0f2fe",
                "surface-container-lowest": "#ffffff",
                "inverse-surface": "#1e293b",
                background: "#f8fafc",
                "on-primary-container": "#1e3a8a",
                "on-tertiary-container": "#0c4a6e",
            },
            borderRadius: {
                DEFAULT: "0.25rem",
                lg: "0.5rem",
                xl: "0.75rem",
                full: "9999px",
            },
            spacing: {
                "margin-desktop": "40px",
                unit: "8px",
                gutter: "24px",
                "container-max": "1280px",
                "margin-mobile": "16px",
            },
            fontFamily: {
                sans: ["Plus Jakarta Sans", ...defaultTheme.fontFamily.sans],
                "label-sm": ["Plus Jakarta Sans"],
                "headline-lg-mobile": ["Plus Jakarta Sans"],
                "body-lg": ["Plus Jakarta Sans"],
                "label-md": ["Plus Jakarta Sans"],
                "body-md": ["Plus Jakarta Sans"],
                "display-lg": ["Plus Jakarta Sans"],
                "headline-md": ["Plus Jakarta Sans"],
                "headline-lg": ["Plus Jakarta Sans"],
            },
            fontSize: {
                "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "700" }],
                "headline-lg-mobile": [
                    "28px",
                    { lineHeight: "1.2", fontWeight: "700" },
                ],
                "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
                "label-md": [
                    "14px",
                    {
                        lineHeight: "1.4",
                        letterSpacing: "0.02em",
                        fontWeight: "600",
                    },
                ],
                "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
                "display-lg": [
                    "48px",
                    {
                        lineHeight: "1.1",
                        letterSpacing: "-0.02em",
                        fontWeight: "800",
                    },
                ],
                "headline-md": [
                    "24px",
                    { lineHeight: "1.3", fontWeight: "600" },
                ],
                "headline-lg": [
                    "32px",
                    {
                        lineHeight: "1.2",
                        letterSpacing: "-0.01em",
                        fontWeight: "700",
                    },
                ],
            },
        },
    },

    plugins: [forms],
};
